services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=smarthome
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASS:-changeme}
      - INFLUXDB_USER=grafana  
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASS:-changeme}
      - TZ=Asia/Hong_Kong

  grafana:
    image: grafana/grafana:9.5.15
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3002:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS:-changeme}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - TZ=Asia/Hong_Kong
    depends_on:
      - influxdb
